### ISSUE TITLE
Writing Workshop: Using Blogging and Great Documentation to Grow Your Open Source Project

### ISSUE THREAD

**Issue by aspittel** [dctech/speaking#13]
## About You

**Your Name:**
Ali Spittel

**Twitter handle (optional):** 
@aspittel

**The best way to reach out to you:**
Email: ali[at]dev.to

**A quick bio:**

Ali is a software engineer at DEV. Before that, she was a lead instructor at General Assembly. She loves Python, JavaScript, and talking about code. She is most interested in the intersection of programming, art, and education.

When Ali's not working, you can find her watching New England sports, competing on CodeWars, taking runs around Capitol Hill, rock climbing, or participating in DC coding community events.

Ali also blogs at dev.to/aspittel where she learns talks about code and her life surrounding it. Her writing has gotten roughly 600,000 readers in the past year.

## Your Talk

**Title:**

Writing Workshop: Using Blogging and Great Documentation to Grow Your Open Source Project

**What your talk is about:**

Writing blog posts and strong documentation for your open source projects is crucial for growing both a user and a contributor base. Your writing is the most effective way to communicate why and how people should use your project. But, you're a software engineer, not a content strategist! How can you effectively target the people you need to with your blog posts and documentation? Also, how can you accurately communicate the goals for your project? This workshop will take you through the writing process, from deciding who you're writing for through what happens after you press publish (or commit to GitHub).

We will start by discussing why strong documentation and blog posts are important for open source projects, and we'll look at some projects who have great content strategies. We will then we'll discuss who your project's target audience is -- whether that's new developers or specialized experts. Then, we'll discuss how to come up with blog post topics, how to make that content engaging and understandable, and how to reach that audience and grow a following.

This workshop will be very hands-on, and attendees will leave with the following completed worksheets:

- A completed worksheet about your target audience and how to reach it
- A list of possible blog post topics
- An outline of the types of documentation needed for your project
- An outline of a blog post

**How long will your talk be?**
- [ ] 5-15 minutes (lightning talk)
- [ ] 20-30 minutes
- [ ] 30-45 minutes
- [x] 60 minutes or more

Can be tailored down, but can be up to 2/3 hrs given the event.

## Meta

**Do you need help crafting your talk?**
- [ ] Yes
- [x] No

**Comment by jackkoppa** [comment]
Hi @aspittel - this sounds excellent! We'd love to have you at [Vue DC](https://www.meetup.com/Vue-DC/), and think a workshop on documenting personal projects could be perfect for our members. Any interest? We typically do the second Wednesday of each month, and have March & May free at the moment

**Comment by aspittel** [comment]
I'm no longer living in DC! Sorry!
