### ISSUE TITLE
Demystifying Algorithmic Complexity

### ISSUE THREAD

**Issue by jbafford** [dctech/speaking#19]
## About You

**Your Name:**
John Bafford

**Twitter handle (optional):** 
@jbafford

**The best way to reach out to you:**
email: john at bafford dot com

**A quick bio:**
John is a freelance software developer with over 20 years of experience in web, desktop, and mobile app development. He also enjoys long-distance hiking.

## Your Talk

**Title:**
Demystifying Algorithmic Complexity

**What your talk is about:**
Complexity theory. Big-O. Constant, linear, logarithmic, and quadratic time versus space trade-offs. What does it actually mean when we say a function or an algorithm is efficient? How can we tell if we can do better? Join me, on this tour through a corner of computer science few developers actively think about, and you’ll walk away with a new way of looking at code and thinking about problems.

This talk is language-agnostic.

**How long will your talk be?**
- [ ] 5-15 minutes (lightning talk)
- [ ] 20-30 minutes
- [ ] 30-45 minutes
- [X] 60 minutes or more

## Meta

**Do you need help crafting your talk?**
- [ ] Yes
- [X] No

**Previously Presented**
Versions of this talk have been given at php[tek] 2017, Nomad PHP, Midwest PHP 2018, and MidDevCon 2019.

**Comment by anitahall102790** [comment]
ACM would love to host this! I'll be contacting you!

**Comment by jackkoppa** [comment]
@dctech/acm-dc 

(still trying out teams as a way to tag potentially interested Meetups)
