### ISSUE TITLE
Auto-reply with a thank you?

### ISSUE THREAD

**Issue by adunkman** [dctech/speaking#24]
It’s awesome that people are submitting talks here!

Sometimes it can feel frustrating if no response is received immediately on a talk — I think we might be able to avoid that, and give some warm fuzzy feels, if we auto-reply to a new submission with a thank you, and explain how the process works. 

What do y’all think? 

I’d be happy to code something up, but we should settle on what to say, if we decide to move forward with this.

**Comment by adunkman** [comment]
I suggest something like:

> Hi @adunkman! 
>
> Thank you for taking the time to submit a talk! Speakers like you make the DC tech community awesome — and we’re glad you’re here.
>
> Rest assured that organizers of quite a few meetups have just been notified of your proposal. 
>
> *Want to target one or two groups specifically?* Mention the group by tagging ‘@dctech/<group>’ — but please avoid tagging groups at random or tagging more than one or two. Thanks for keeping this group productive and spam-free!
>
> *Not interested in giving this talk anymore?* Not a problem at all! Go ahead and close this issue, so we know not to bother you about it.

**Comment by jackkoppa** [comment]
I like it! No proposed changes from me; I think something like that is perfect. This would be as an on-issue comment, right?
