### ISSUE TITLE
More Than Making Code Work: Privacy By Design in Product Development

### ISSUE THREAD

**Issue by pumzi** [dctech/speaking#25]
## About You

**Your Name:**
Pumzi

**Twitter handle (optional):** 

**The best way to reach out to you:**

**A quick bio:**

## Your Talk

**Title:**
Centering Consumer Privacy & Security in Product Development & Design

**What your talk is about:**
Are you interested in user centered privacy and security best practices?  The goal of this workshop is to introduce and receive feedback from developers, designers, and other technologists on [The Digital Standard](https://www.thedigitalstandard.org/the-standard).  The Digital Standard is an open source guideline that Consumer Reports (the organization that is hosting me as a part of my fellowship) uses to test and rate the privacy and security of consumer software, digital platforms and services, and Internet-connected products.  Consumer Reports is seeking contributions to the Digital Standard from members of the Tech Community in order to shape, refine, test and improve the standard in order to ensure it is comprehensive, effective, and up-to-date in a rapidly-changing marketplace. 

**How long will your talk be?**
- [ ] 5-15 minutes (lightning talk)
- [x] 20-30 minutes
- [x] 30-45 minutes
- [ ] 60 minutes or more

## Meta

**Do you need help crafting your talk?**
- [ ] Yes
- [ X] No

**Comment by necaris** [comment]
@SelinaMusuta we'd be interested in this talk at [DC Python](https://www.meetup.com/dcpython/), possibly for July or August, if that'd be of interest to you?

**Comment by SelinaMusuta** [comment]
@necaris I'm interested in presenting in August! What are next steps?

**Comment by necaris** [comment]
@SelinaMusuta could you shoot me an email at `rami.chowdhury@gmail.com` and we can continue the conversation? Don't want to clutter up this issue ;-)

**Comment by jenpen** [comment]
Tech Talk DC hosted this discussion in March 2019 and it was so good! Thanks so much to @SelinaMusuta for a great presentation and great topic.
