### ISSUE TITLE
Getting the word out about this repo

### ISSUE THREAD

**Issue by adunkman** [dctech/speaking#4]
As @aspittel excellently suggested in Slack, it’d be great to get the word out about this to people who are interested in submitting talks — and had thrown out Monday (Jan 21, MLK Day) as a date to get some wind in our sails. 

Let’s coordinate! Maybe we can decide how that happens, who plans on publishing it where, and we can share the effort of writing up some blurbs.

**Comment by aspittel** [comment]
Awesome, was planning on doing twitter, the DC tech slack, and women who code's slack. Would love other people to tweet or post on other social media too (or someone else can do slack as well). I'll also probably post using my meetups' accounts too.

**Comment by adunkman** [comment]
On Slack, I think folks in `#conference-speaking`, `#meetups-and-events`, `#ship-it`, and maybe `#dctech-general` would be interested. Trying to find other meetups to get in on the ground floor. 🚀 

I’m personally jazzed about this, so I’ll be announcing this on my personal Twitter as well.

**Comment by adunkman** [comment]
This went out this morning — [tweet for reference](https://twitter.com/aspittel/status/1087405792058359809?s=21). Great work!
