### ISSUE TITLE
HTTP2 Fast 2 Performant

### ISSUE THREAD

**Issue by uncompiled** [dctech/speaking#41]
## About You

**Your Name:** Chris Nguyen

**Twitter handle (optional):** uncompiled

**The best way to reach out to you:** DCtech Slack

**A quick bio:**

I have a BS & MS in Computer Science, but I'm most likely unable to implement A* Search or invert a binary tree during a technical interview.  I've been a tech lead and a project manager, but Excel and PowerPoint did not spark joy, so I threw them away to focus on building things.  I'm currently a software engineer at The Washington Post where I build `Web Things`™ and try not to break the internet.

## Your Talk

**Title:** HTTP2 Fast 2 Performant _(title subject to change)_

**What your talk is about:**

This talk is an introduction to HTTP2, it's implementation, and some anti-patterns.  While the HTTP2 specification is mostly locked down, the implementation of some of the more exciting features, such as H2 Server Push are still changing.  Work is still being done within the web standards community to make Server Push and Resource Preloading work better, but this talk will help web developers understand how everything works and how HTTP2 affects our current development practices, such as resource bundling.

> NOTE: I've given [another talk](https://speakerdeck.com/uncompiled/navigating-the-critical-path) that's a precursor to this.  That talk was an introduction to how browsers work and explained the role of the network (HTTP, DNS, TCP) in fetching resources.  This talk is sort of an evolution of that presentation that focuses solely on how HTTP2 affects web development.

**How long will your talk be?**
- [ ] 5-15 minutes (lightning talk)
- [ ] 20-30 minutes
- [x] 30-45 minutes
- [ ] 60 minutes or more

## Meta

**Do you need help crafting your talk?**
- [ ] Yes
- [x] No

**Comment by jackkoppa** [comment]
@dctech/dcjs
