### ISSUE TITLE
Introduction to GraphQL

### ISSUE THREAD

**Issue by mmlumba** [dctech/speaking#50]
## About You

**Your Name:** Marian Lumba

**Twitter handle (optional):** mmlumba

**The best way to reach out to you:** Twitter (see above) and email (mmlumba@gmail.com)

**A quick bio:** Marian is a front end developer who likes to use new technologies to solve existing problems. Her tools of choice include React, GraphQL, and Node.JS. She builds JavaScript apps with Demosphere, a company that provides tech solutions for sports organizations. In her spare time she is an event organizer for Women Who Code, a kickboxer, and a D.C. restaurant explorer.

## Your Talk

**Title:** Introduction to GraphQL

**What your talk is about:** This talk briefly addresses the following questions: What is GraphQL? How is it different from REST? How can you use it with an existing data set?

**How long will your talk be?**
- [ ] 5-15 minutes (lightning talk)
- [x] 20-30 minutes
- [ ] 30-45 minutes
- [ ] 60 minutes or more

## Meta

**Do you need help crafting your talk?**
- [x] Yes
- [ ] No

**Comment by adunkman** [comment]
![Drew Nickerson says: Kudos to Marian for packing the house last night with her “Intro to GraphQL” presentation! It was one of the largest Tech Talk DC events we’ve hosted and we _almost_ ran out of tacos :districttaco:](https://user-images.githubusercontent.com/14930/60280869-c9a2fe80-98d1-11e9-9269-77418da3d0b9.png)
