### ISSUE TITLE
A Neurobiologist’s Guide [to Debugging Your Brain / to Team Empowerment]

### ISSUE THREAD

**Issue by caseywatts** [dctech/speaking#51]
## About You

**Your Name:** Casey Watts

**Twitter handle (optional):** [@kyloma](https://twitter.com/kyloma)

**The best way to reach out to you:** DCTech Slack chat `@caseywatts`

**A quick bio:** 
"Casey Watts!" never leaves home without bubbles. His super-power is empathy and helping others become more empathetic. He has a background both in psychology and in software development, making him well prepared to discuss psychology with developers. He studied neurobiology at Yale University, and he co-published a few neurobiology papers.

## Your Talk
"A Neurobiologist's Guide" contains two halves: "Debugging Your Brain" and "Team Empowerment". These two parts build on each other a lot, and they're best presented together. The two can be split apart, but a lot of crossover is lost. Casey has given this talk 16+ times at meetups, conferences, and companies; it's pretty polished at this point ✨ 

**Title:**
"A Neurobiologist’s Guide" (part A+B, 50 min)
or
"A Neurobiologist’s Guide to Debugging Your Brain" (part A, 25 min)
or
"A Neurobiologist’s Guide to Team Empowerment" (part B, 25 min)

**What your talk is about:**
A useful-psychology double-whammy: (A) Developers are great systems thinkers. Surprise: your brain is a system too! Reframe frustration into accomplishment, and become a more effective and bubbly person using a frontal cortex feedback loop. (B) Want your team to be the happiest, most productive team around? Recent psychology research reveals one key attribute of the most successful teams, and it's within your influence.

**How long will your talk be?**
I can do this talk a short form in 25 minutes, or a longer form in 50 minutes (see above).

- [ ] 5-15 minutes (lightning talk)
- [x] 20-30 minutes
- [ ] 30-45 minutes
- [x] 60 minutes or more

## Meta

**Do you need help crafting your talk?**
- [ ] Yes
- [x] No

**Comment by thoppe** [comment]
Hi @caseywatts this seems neat! We are [DC Hack && Tell](https://dc.hackandtell.org/) and would love to hear a version of it. The only catch is the length of time -- you'll have to make it 5 minutes or less as that is the format of the talk. Seek us out on the webpage or on [Twitter](https://twitter.com/dchackandtell) if you have any more questions.

**Comment by caseywatts** [comment]
@thoppe that's awesome! I never would've thought to bring this to Hack & Tell, thanks for suggesting it :)

I'll mull over how to shorten it even more, 5 minutes is a fun challenge. Hopefully I'll have something distilled down in a month or two 🤞
