### ISSUE TITLE
Getting your first Software Engineering job after dropping out of college

### ISSUE THREAD

**Issue by SteveChenDC** [dctech/speaking#62]
## Talk Request

**Topic(s):** Overcoming the Need to Please - Getting your first Software Engineering role after dropping out of college* _(A practical guide to networking)_

**Additional Notes:**
This will be a networking and job strategy talk by a first generation Asian-Am with immigrant parents that emphasized traditional higher education

**Bio:** Steve Chen is a Software Engineer in Test at Framebridge. He currently works mainly with Ruby to build tests, processes, and documentation across distributed teams/systems for a hyper-growth custom framing startup. He also moonlights as a Product Manager on Booster. His resume includes Frontend work with React at GrubHub, on-demand delivery jobs, freelancing, and 3to5something startups. 

He's also hosted/organized meetups such as DCJS, NodeSchool, and DC Code & Coffee. In his spare time, you can see him zipping around on his electric skateboard, fly fishing in MD, or at your local DC meetup!

_*he did rejoin shortly after getting his first tech job to finish his senior year at University of Maryland for a BS in Information Systems Management. The first in his family to receive a degree_

**What would the ideal length be?**
- [x] 5-15 minutes (lightning talk)
- [x] 20-30 minutes

## On Behalf Of

**Requesting people or Meetups:**
Bootcamp Grads! 

**The best way to reach out to them:**
Ideally stevechenweb@gmail.com or @steve chen on dctech.chat Slack

**Comment by csexton** [comment]
This talk would be great for Arlington Ruby, especially if you can throw in some fly fishing tips and tricks 😄🎣 

If you are interested I'll ping you about schedule on the slack.

**Comment by pburkholder** [comment]
We'd like to have a DevOpsDc meetup around careers and getting started. Would you be up for that?  Looking at April 9, May 14 or Jun 11. I'm @pburkholder on Twitter etc.
