### ISSUE TITLE
Avoiding Pitfalls of Non-Technical Managers

### ISSUE THREAD

**Issue by VictoriaGuido** [dctech/speaking#67]
## About You

**Victoria Guido**

**victori_ousg** 

**Twitter DM open**

**An Operations Manager at Blackstone Federal, Victoria Guido lives to inspire change, compassion, and curiosity in upcoming leaders in technology. She leads several local technology and management communities in her hometown of Washington, DC - including DevOps DC, Women Who Code, DC Atlassian User Group, and the Project Management Institute. With over 12 years of experience in IT in a broad range of roles, she has led major cloud, cybersecurity, and agile software development projects for large Federal Agencies and private financial institutions.**

## Your Talk

**Avoiding Pitfalls of Non-Technical Managers**

**What your talk is about:**
Technology is really complicated and changes every day. Even leaders with a technical background and deep understanding have trouble keeping up - it’s virtually impossible to be an expert on every single aspect of a product. How can you help your team if you have no idea what anyone is talking about? Engineers and developers have all experienced the frustration and difficulties in being led by someone deemed “non-technical”, from unrealistic deadlines or solutions being promised to the customer, to a lack of trust and complete breakdown in communication. Explore how to create a culture of learning, form a cross-functional team, and play to your strengths. Start by removing the boundary between “technical” and “non-technical” and being specific with the skillsets, history, and experience all of your team members are bringing to the table. At the end of the day, everyone appreciates a good manager no matter what technical skills they may or may not  have.

**How long will your talk be?**
- [x] 5-15 minutes (lightning talk)
- [x] 20-30 minutes
- [ ] 30-45 minutes
- [ ] 60 minutes or more

## Meta

**Do you need help crafting your talk?**
- [ ] Yes
- [x] No

**Comment by csexton** [comment]
Interesting topic -- would you be interested in presenting at @dctech/arlington-ruby ?
