### ISSUE TITLE
The Value of Diversity & Inclusion to DevOps

### ISSUE THREAD

**Issue by VictoriaGuido** [dctech/speaking#68]
## About You

**Victoria Guido**

**victori_ousg** 

**Twitter**

**A quick bio:**
An Operations Manager at Blackstone Federal, Victoria Guido lives to inspire change, compassion, and curiosity in upcoming leaders in technology. She leads several local technology and management communities in her hometown of Washington, DC - including DevOps DC, Women Who Code, DC Atlassian User Group, and the Project Management Institute. With over 12 years of experience in IT in a broad range of roles, she has led major cloud, cybersecurity, and agile software development projects for large Federal Agencies and private financial institutions.

## Your Talk

**The Value of Diversity & Inclusion to DevOps**

**What your talk is about:**
Research shows that diverse, inclusive teams are better at solving problems, more creative, and higher performing. The underlying truth in the value of D&I lies in the evolutionary psychology of the human brain - how we learn, empathize with others, and develop new ideas. 

Have you ever faced an issue with a server or application for hours on end, only to have someone else come over and help you figure it out in two seconds? That’s the value of bringing in a different perspective, changing the algorithm you’re using to solve a problem and ultimately getting a better result.

In this talk we’ll share common steps, lessons learned, and tips & resources that can help you personally OR as an organization work toward creating a diverse and inclusive environment. We’ll highlight the changes in our company - from our hiring practices to the art on the walls - and share the value we’ve found in truly investing in D&I and the impact on our business.

**How long will your talk be?**
- [x ] 5-15 minutes (lightning talk)
- [x ] 20-30 minutes
- [ ] 30-45 minutes
- [ ] 60 minutes or more

## Meta

**Do you need help crafting your talk?**
- [ ] Yes
- [x ] No

**Comment by lamroger** [comment]
Excited to host @VictoriaGuido at the DC DevOps for Startups meetup May 7th.
Sign up below!
https://www.meetup.com/DC-DevOps-for-Startups/events/260091241/

**Comment by jenpen** [comment]
hi @VictoriaGuido - would you be interested in speaking at Tech Talk DC's October meetup? We would love to have you speak. Feel free to PM me on dctech slack (@jenpen). 

https://www.meetup.com/TechTalkDC/
