### ISSUE TITLE
Application Secret Management in AWS

### ISSUE THREAD

**Issue by kave** [dctech/speaking#74]
## About You

**Your Name:** Emmanuel Apau

**Twitter handle (optional):**  @technoGrouch

**The best way to reach out to you:** Email `etapau` at gmail

**A quick bio:**  AWS Certified Site Reliability specialist with 9 years of experience developing innovative automation solutions using Devops best practices for clients with Python/Golang. Experience in both the public and private sectors, providing services that engage Agile best practices, scalable cloud architectures, and modern continuous integration & deployment standards.

## Your Talk

**Title:** Application Secret Management in AWS

**What your talk is about:** Taking advantage of AWS Parameter Store & some automation magic to make secret change management a problem of the past.
We'll talk about:

- Why management of secrets
- Use Cases
- DB Password rotations process
- LastPass vs Parameter Store vs Vault
- OSS Tools

**How long will your talk be?**
- [ ] 5-15 minutes (lightning talk)
- [ ] 20-30 minutes
- [X] 30-45 minutes
- [ ] 60 minutes or more

## Meta

**Do you need help crafting your talk?**
- [ ] Yes
- [X] No

@dctech/techtalkdc

**Comment by uncompiled** [comment]
@dctech/devopsdc might be interested in this too!

**Comment by pburkholder** [comment]
@technoGrouch It's true - @devopsdc would be interested in the secret mgmt talk. We'll be in touch if you're interested. Maybe August or September (unless we get cancellations) - might that work?

**Comment by kave** [comment]
@pburkholder yea sure! lets make it happen
