### ISSUE TITLE
Intro to Mobile App development with Vue Native

### ISSUE THREAD

**Issue by duaimei** [dctech/speaking#77]
## About You

**Your Name:**
Amy Detwiler

**Twitter handle (optional):** 
@duaimei

**The best way to reach out to you:**
amyd on dctech slack

**A quick bio:**
I am currently a software engineer at Optoro. We use VueJS and Rails for our product, and this led to my interest in learning Vue Native for mobile app development.

## Your Talk
A hands-on introduction to Vue Native. 

**Title:**
Hello Weather: An Introductory Vue Into Mobile App Development

**What your talk is about:**

Why choose between developing for Android and IOS, when you can develop for both at the same time using nothing more than (essentially) basic HTML, CSS, and JavaScript? This workshop will focus on getting a My First App out the door by using the theme of a basic Weather App.

**How long will your talk be?**
- [ ] 5-15 minutes (lightning talk)
- [ ] 20-30 minutes
- [ ] 30-45 minutes
- [ x] 60 minutes or more

## Meta

**Do you need help crafting your talk?**
- [x ] Yes - I have a good idea of what I will be doing, but feedback before the talk would be nice.
- [ ] No

**Comment by bencodezen** [comment]
@duaimei We would love to have you come speak at @dctech/vuedc! I've reached out to you on the DC Tech slack, but let me know if you didn't get my message and we'll sync up another way!
