### ISSUE TITLE
Creating a data driven app with GraphQL and Apollo Client

### ISSUE THREAD

**Issue by mmlumba** [dctech/speaking#81]
## About You

**Your Name:** Marian Lumba

**Twitter handle (optional):** mmlumba

**The best way to reach out to you:** Twitter (see above) and email (mmlumba@gmail.com)

**A quick bio:** Marian is a front end developer who likes to use new technologies to solve existing problems. Her tools of choice include React, GraphQL, and Node.JS. She builds JavaScript apps with Demosphere, a company that provides tech solutions for sports organizations. In her spare time she is an event organizer for Women Who Code and a D.C. restaurant explorer.

## Your Talk

**Title:** Creating a data driven app with GraphQL and Apollo Client

**What your talk is about:** This talk will briefly explain how GraphQL works and how information from GraphQL can be displayed in a stateful application via Apollo Client.

**How long will your talk be?**
- [ ] 5-15 minutes (lightning talk)
- [x] 20-30 minutes
- [x] 30-45 minutes
- [ ] 60 minutes or more

## Meta

**Do you need help crafting your talk?**
- [ ] Yes
- [ ] No

**Comment by pburkholder** [comment]
Sounds interesting. Did this get recorded anywhere?

**Comment by mmlumba** [comment]
I am planning to do this talk for React DC, but I closed the issue so that I can commit to doing this talk for one meetup at a time

**Comment by mmlumba** [comment]
Not sure if anyone wanted an update, but it's now an official meetup event: https://www.meetup.com/React-DC/events/268276525/
