### ISSUE TITLE
Kick Those Scripts to the Sandbox: Web Security is Your Responsibility 

### ISSUE THREAD

**Issue by adunkman** [dctech/speaking#89]
## About You

**Your Name:** Andrew Dunkman

**Twitter handle (optional):** @adunkman

**The best way to reach out to you:** via this issue, just @-me!

**A quick bio:**

## Your Talk

**Title:** Kick Those Scripts to the Sandbox: Web Security is Your Responsibility 

**What your talk is about:** Do you want Tweets or your latest Instagram food picture to display nicely in your site? Just load this third-party script into your site — never mind what it does! … err, what’s the difference between third-party scripts and a cross-site scripting attack again? Can’t third-party scripts steal user credentials, track users without their consent, and hijack your site for advertising purposes? In this talk, we’ll discuss different ways of sandboxing these scripts to increase your site’s security, stability, and protect the privacy of your users. You’ll leave with an understanding of the latest browser features designed to protect you and your users.

**How long will your talk be?**
- [ ] 5-15 minutes (lightning talk)
- [x] 20-30 minutes
- [x] 30-45 minutes
- [ ] 60 minutes or more

## Meta

**Do you need help crafting your talk?**
- [ ] Yes
- [x] No

**Comment by adunkman** [comment]
Previously given at DC JavaScript, [slides](https://speakerdeck.com/adunkman/kick-those-scripts-to-the-sandbox-at-dc-javascript).

**Comment by jackkoppa** [comment]
Hey @adunkman - this sounds excellent for @dctech/vuedc. We'd love to have you!

I'll reach out to coordinate dates, if you're interested

**Comment by csexton** [comment]
@adunkman oooo, I like the topic -- interested in giving it at @arlingtonruby?

**Comment by adunkman** [comment]
Sounds great x2! Looks like it’ll be tentatively mid December with @jackkoppa — maybe January @csexton? What dates work well?

**Comment by csexton** [comment]
Sounds good @adunkman. I'll get back to you with dates 📆

**Comment by VictoriaGuido** [comment]
hey @adunkman  ! Any availability to give this talk at DevOps DC? we have an opening for Tuesday, Jan 14th at Excella but also later in the year would be cool too

**Comment by adunkman** [comment]
Hi @VictoriaGuido! I’m interested, but can’t do the 14th — would be happy to plan for a future date though.
