### ISSUE TITLE
Debugging Your Brain Workshop

### ISSUE THREAD

**Issue by caseywatts** [dctech/speaking#92]
## About You

**Your Name:** Casey Watts

**Twitter handle (optional):** @kyloma

**The best way to reach out to you:** DC Tech Slack (@caseywatts)

**A quick bio:**
  Casey Watts is the author of [Debugging Your Brain](https://www.debuggingyourbrain.com) (DYB), a clear applied psychology book and a concise self-help book. His book brings together two of his backgrounds: psychology and software development. Casey studied neurobiology at Yale University, and he is a co-author on [several neurobiology papers](https://pubmed.ncbi.nlm.nih.gov/?term=Watts+and+Schafe). He has also worked in software development for 10 years, including at [Heroku](https://blog.heroku.com/authors/casey-watts). Casey can play ten musical instruments, and he owns one in every color of the rainbow (most recently a white accordion). Casey has been an active member of the DC Tech community since 2015. 

## Your Talk

**Title:** Debugging Your Brain Workshop

**What your talk is about:**
The human brain is buggy. Sometimes your mind distorts reality, gets frustrated with shortcomings, and spirals out of control. With practice, you can debug your brain. Catch those distortions of reality, transform those frustrations into insight, and short-circuit those downward spirals.

In this workshop you will get a chance to practice each core idea from Casey’s book [Debugging Your Brain](https://www.debuggingyourbrain.com): Modeling The Brain, Cognitive Behavioral Therapy, Introspection, Identifying Inputs, Experience Processing, Experience Validation, and Cognitive Restructuring.

Debugging Your Brain is a clear applied psychology book and a concise self-help book, available in all three formats: printed book, eBook and audiobook: debuggingyourbrain.com

**How long will your talk be?**
- [ ] 5-15 minutes (lightning talk)
- [ ] 20-30 minutes
- [ ] 30-45 minutes
- [x] 60 minutes or more

## Meta

**Do you need help crafting your talk?**
- [ ] Yes
- [x] No

**Comment by csexton** [comment]
Oooo, I wanna go to that talk! Love to host you at Arlington Ruby.

**Comment by caseywatts** [comment]
Yay! I'd love to do this for Arlington Ruby.
I'll reach out on Slack to coordinate @csexton :)
